const GET_DATA_LODING = "GET_DATA_LOADING"
const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
const GET_DATA_FAILURE = "GET_DATA_FAILURE"

const ADD_DATA_LOADING = " ADD_DATA_LOADING"
const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS"
const ADD_DATA_FAILURE = "ADD_DATA_FAILURE"













export {GET_DATA_FAILURE,GET_DATA_LODING,GET_DATA_SUCCESS,ADD_DATA_FAILURE,ADD_DATA_SUCCESS,ADD_DATA_LOADING}